### ISSUE TITLE
没用了

### ISSUE THREAD

**Issue by Peterhaiker** [the0demiurge/MyScripys-linux#1]
大佬，您好，今天晚上突然就不好了。配置信息完全正确，检查过很多遍。手机上用的ssr客户端还是非常快，电脑就完全连不上了

**Comment by the0demiurge** [comment]
把配置信息里面为空的条目删掉再试试看？
比如`obfs="";`这样的项目

**Comment by Peterhaiker** [comment]
IPv6 support
stopped
IPv6 support
2017-10-11 13:02:52 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
started
Testing Connection...
curl: (7) Failed to connect to localhost port 1080: Connection refused
我都删掉试了，然后电脑设置里面的那个代理配置界面我也关掉了，一直有这个问题，弄了好长时间了不知道怎么搞

**Comment by the0demiurge** [comment]
ssr uninstall然后再ssr install，然后重新再试试看吧：）
然后可以删掉/usr/local/share/shadowsocksr

**Comment by HTML50** [comment]
hi 初次使用lubuntu翻墙

```
bt@genesis:~$ sudo ssr start
IPv6 support
2017-10-11 15:56:17 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
started
Testing Connection...
curl: (52) Empty reply from server
```

发现使用`curl ip.cn --socks5 'localhost:1080' `就返回空。
在windows下倒是正常使用。

请问是哪个环节出了问题

**Comment by the0demiurge** [comment]
用ssr log看一下日志吧，把日志贴一下？
@Peterhaiker @HTML50

**Comment by Peterhaiker** [comment]
现在虽然显示连上了，但是还是不能科学上网
IPv6 support
stopped
IPv6 support
2017-10-11 19:23:04 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
started
Testing Connection...
当前 IP：47.52.100.54 来自：香港特别行政区 阿里云
上面是重启连接显示的信息，下面是日志：
2017-10-11 19:02:00 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]
2017-10-11 19:10:23 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [OAkPYX] method [aes-128-ctr] obfs [http_simple] obfs_param [37485738.baidu.com]
2017-10-11 19:10:23 INFO     local.py:54 starting local at 127.0.0.1:1080
2017-10-11 19:10:23 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]
2017-10-11 19:10:38 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [OAkPYX] method [aes-128-ctr] obfs [http_simple] obfs_param [37485738.baidu.com]
2017-10-11 19:10:38 INFO     local.py:54 starting local at 127.0.0.1:1080
2017-10-11 19:10:38 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]
2017-10-11 19:23:04 INFO     local.py:50 local start with protocol[auth_aes128_md5] password [OAkPYX] method [aes-128-ctr] obfs [http_simple] obfs_param [37485738.baidu.com]
2017-10-11 19:23:04 INFO     local.py:54 starting local at 127.0.0.1:1080
2017-10-11 19:23:04 INFO     asyncdns.py:324 dns server: [('127.0.1.1', 53)]

**Comment by the0demiurge** [comment]
这就是代理设置的问题了，浏览器应当设置相应的代理，可以借助相关插件，比如SwitchyOmega

**Comment by Peterhaiker** [comment]
第一次用的时候没有设置代理也可以的。现在又发现了一个新状况：我刚刚ssr config换了另一个节点后出现了如下信息：
IPv6 support
Traceback (most recent call last):
  File "local.py", line 81, in <module>
    main()
  File "local.py", line 43, in main
    config = shell.get_config(True)
  File "/home/caplinux/.local/share/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/home/caplinux/.local/share/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/home/caplinux/.local/share/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/home/caplinux/.local/share/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/home/caplinux/.local/share/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/home/caplinux/.local/share/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/home/caplinux/.local/share/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found

**Comment by Peterhaiker** [comment]
而且我ping google.com ping不通

**Comment by Peterhaiker** [comment]
上面那个问题我安装了libsodium后解决了

**Comment by Peterhaiker** [comment]
我现在用了那个代理浏览器可以用了，也不知道之前没用代理为啥也可以

**Comment by Peterhaiker** [comment]
最新情况：只有浏览器能用，ping还是不通……

**Comment by the0demiurge** [comment]
那是因为你的ping没有走代理= =

**Comment by the0demiurge** [comment]
@Peterhaiker 把你之前发过的日志重新编辑一下吧，服务器帐号密码都泄露了

**Comment by Peterhaiker** [comment]
好的，我删掉了，谢谢

**Comment by wuguowei1994** [comment]
同样的问题，相同的配置，在windows系统下可以翻墙成功，在linux系统下总是报错：curl: (52) Empty reply from server
